# Generated by Django 5.1.5 on 2025-01-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_nationalize', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='data',
            new_name='country',
        ),
        migrations.AddField(
            model_name='person',
            name='count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
